name = "Hugo Book Template"
license = "MIT"
licenselink = "https://github.com/gettypubs/hugo-book-template/blob/master/LICENSE.md"
description = "Skeleton for rapid development with hugo"
homepage = "github.com/gettypubs/hugo-book-template"
tags = ["", ""]
features = ["", ""]
min_version = 0.14

[author]
  name = "Eric Gardner"
  homepage = "egardner.github.io"
